language: java
sudo: false
jdk:
- openjdk8
branches:
  only:
  - master
  - develop
  - /^feature.*$/
cache:
  directories:
  - $HOME/.m2/repository
  - $HOME/.m2/wrapper
before_install:
- export TZ=Australia/Canberra
- date
- mkdir -p ~/.m2
- wget -q -O ~/.m2/settings.xml https://raw.githubusercontent.com/AtlasOfLivingAustralia/travis-build-configuration/master/travis_maven_settings.xml
after_success: '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && ./mvnw deploy -DskipTests=true'
env:
  global:
  - secure: TisL1LS14qLOa78J/CKUGXI+YXc1ZewSWIbzzjW/mCT6i1CCi9BPSTgzWGVVTjEkPYyMdPwgHdn/L9ocsyO056JjMWhwboahtfFd7IvmDhywdENlK/1xvjN9z5LVDgXzTGJTNs/7n4W/11iIsoG+17bRYtKcXl1QesEimxw/HhLrB41pxKc9fUy6HwMti5GmnrhhoKW9c/tZoE2KxInyDbxk4lBCs8TSwOx/ErWWRoFkAxnjVBVOY0W/j2ykBFswMfQhREqttkmkHgt2amgKguL49lzvZ8AYIx97cAy1QI2XIo35ae9MqFCfLfDkOfQoa0nKIuMLV7HP2ILqMCzj038CD/KNM0xkHbDQ9CXIsw/e/o8cnFLj6H/W5+072TBoQSiC9VfLkC+ezFXu2hAo7ECTaRbSUy+Jp0S6+ZSD9zI68zbU9NRFmmRHIDlPjS0YvwVjuFEu1dfRsjbX0nt+MJ85n7gpN0B5CX4PhB1g7eONS11nIBpUFOUO3Gdt2yYWtzVrheaeBis7pzf6sq+SePdbIMvOwnUXBIWllyTe4jWq+7qtOe52LWQMEm5MoKxlR5Jm7KqFQqgTSYHxxxtIsq+m8oe3zWhO97mflfvlAv4pIADMFxfDnRZvzXl0WxTgMXi5MRwNvLFZqIyod7RBezsI9sMMBWHU+xa7I+rCg9Q=
  - secure: Jj2lCcwrgBcpO3uiKUPosPwitZFjIpCnkKCJudJuPbPLUzAQbi7hPR/uO0e8w7ckm+KOq7cde6iJSHUnNDG7c7EmyaW/zfmhD9FnJLLamSjpXlWwkiBgowXe9UXOtAtgZgjbGGU4BeqWm8uyVJoCLXvx+wA9MCshPgK1f6mZjFX+F/eN8MOie31zTJKKxAPiTXTdjhTUDaC8wRKhXbazLthemXskqHzLmx5dile/QMkz9/bG9EkEWS+CLzFIV1wpPIZTaQWV4XkNqZ3fFDW4ANGMLCuRf022K4odZtXfE8YdHpeVnLzI7E9cauJ/vgp4VxlsECoRpcXIyHyQMTgEquN7ezuhvzYEw3i9tpTQZKTPZP1FFCBdny3N6gMyT98SqA52NKOpBk4MaC2gSC8SHbpdFyiFWY0I5gVMfrZ6atvA/nkq1x7bnZGXgUrVEupyDmcJuy17LY9mIt6f+kPl6hFe6F+GLe4gHq44GbEAFoM8reACQk0szDGsa3iGQEhmTxVGAOWB47dmtugMMQNKGrUl7wFWJdqJUw5R6709+l5XizZR9+7cADUj+i/o1+/iCwtEz3UoghYj3EdP9Sd3NezAzrsW3trtQih5JF9uIoZapffMQHxeSrSxK4coQfVu8sZfDgpcs2eSqxj+fl29689ezXc3HFCgW9qEEyvpjjI=
