info:
  description: ALA CAS Configuration

# Enable these for Spring Boot actuator (required for Spring Boot Admin client)

#endpoints:
#  enabled: true
#security:
##  ignored[0]: "/**"
#  filterOrder: 0
#  user:
#    name: admin
#    password: secret
#    role:
#      - ACTUATOR
#  basic:
#    enabled: true
#    authorizeMode: role
#    realm: ALA CAS
#    path:
#      - /status/**
#management:
#  security:
#    enabled: true
#    roles: ACTUATOR

# Enable these to connect to a Spring Boot Admin server

#spring:
#  boot:
#    admin:
#      url: https://bootadmin.example.org:8444
#      client:
#        managementUrl: ${cas.server.prefix}/status
#        name: ALA CAS
#        metadata:
#          user:
#            name: xxxxxxxx
#            password: xxxxxxx


jndi:
  hikari:
    - name: jdbccas
      driverClass: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost/cas[?serverTimezone=Australia/Sydney]
      user: username
      password: password
      dataSourceProperties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048

flyway:
  url: jdbc:mysql://localhost/cas[?serverTimezone=Australia/Sydney]
  user: root
  password: password

cas:
  adminPagesSecurity:
#    ip: ".*"
#    actuatorEndpointsEnabled: true
  authn:
    jdbc:
      query:
# Use this for a Tomcat provided JNDI DataSource
#        - dataSourceName: java:comp/env/jdbc/cas
        - dataSourceName: jdbccas # For the bcrypt password encoder
        - dataSourceName: jdbccas # For md5 password encoder
    attributeRepository:
      jdbc:
        - dataSourceName: jdbccas
    pac4j:
      facebook:
        id: xxxxxxxxxxxxxxx
        secret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        scope: public_profile,email
      twitter:
        id: xxxxxxxxxxxxxxxxxxxxxxxxx
        secret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      google:
        id: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        secret: xxxxxxxxxxxxxxxxxxxxxxxx
        scope: EMAIL_AND_PROFILE
  monitor:
    endpoints:
#      enabled: true
    jdbc:
      validationQuery: /* ping */ SELECT 1
      dataSourceName: jdbccas
  ticket:
    registry:
      jpa:
        ddl-auto: update
        url: jdbc:mysql://localhost/casTicketRegistry[?serverTimezone=Australia/Sydney]
        user: username
        password: password
        signing:
          key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        encryption:
          key: xxxxxxxxxxxxxxxx
  tgc:
    encryptionKey: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    signingKey: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  webflow:
    signing:
      key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    encryption:
      key: xxxxxxxxxxxxxxxx

ala:
  userCreator:
    userCreatePassword: random-default-password-here
    jdbc:
      dataSourceName: jdbccas
#      sql: sp_create_user
